name: Check POP MART Stock

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore stock history
        uses: actions/cache/restore@v4
        with:
          path: |
            stock_history.json
            uptime_history.json
          key: stock-history-${{ github.sha }}-${{ github.run_number }}
          restore-keys: |
            stock-history-${{ github.sha }}-
            stock-history-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run stock checker
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          COLLECTION_ID: ${{ secrets.COLLECTION_ID }}
          KEYWORD: ${{ secrets.KEYWORD }}
          DEBUG_MODE: ${{ secrets.DEBUG_MODE }}
        run: |
          python check_stock.py

      - name: Save stock history
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            stock_history.json
            uptime_history.json
          key: stock-history-${{ github.sha }}-${{ github.run_number }}
